/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JDialog.java to edit this template
 */

/**
 *
 * @author ACER
 */
public class DialogTambahSparepart extends javax.swing.JDialog {
    
    // Variabel array untuk menyimpan data yang akan dikirim ke form utama
    Object[] dataBaru = null;
    
    // Array statis bertindak sebagai database sementara penyimpanan stok.
    // Indeks: 0 (Kosong/Pilih), 1 (SSD), 2 (RAM), 3 (RAM), 4 (HDD)
    public static int[] stokGlobal = {0, 15, 8, 5, 14};
    
    // Indeks: 0 (Kosong), 1 (SSD), 2 (RAM), 3 (RAM), 4 (HDD)
    public static String[] kodeGlobal = {"-", "SP-001", "SP-002", "SP-003", "SP-004"};

    /**
     * Creates new form DialogTambahSparepart
     */
    public DialogTambahSparepart(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        
    }
    
    private void hitungSubtotalSparepart() {
        try {
            // Ambil nilai harga dari tfHargaSatuan (Harga Satuan)
            // Jika kosong, anggap 0
            String teksHarga = tfHargaSatuan.getText();
            double harga = teksHarga.isEmpty() ? 0 : Double.parseDouble(teksHarga.replace(".", ""));
            
            // Ambil nilai angka dari sJumlah (Jumlah)
            // sJumlah mengembalikan tipe data Object, jadi harus di-casting ke Integer
            int jumlah = (Integer) sJumlah.getValue();
            
            // Hitung subtotal
            double subtotal = harga * jumlah;
            
            // Buat desimal format lokal di dalam pop-up
            java.text.DecimalFormat df = new java.text.DecimalFormat("#,###");
            java.text.DecimalFormatSymbols dfs = new java.text.DecimalFormatSymbols();
            dfs.setGroupingSeparator('.');
            df.setDecimalFormatSymbols(dfs);
            
            // Tampilkan hasilnya ke tfSubtotal (Subtotal) tanpa angka desimal (.0f)
            tfSubtotal.setText(df.format(subtotal));
        } catch (Exception e) {
            // Jika ada error (misal harga belum dipilih), set subtotal jadi 0
            tfSubtotal.setText("0");
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        cbSparepart = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        tfHargaSatuan = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        sJumlah = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        tfSatuan = new javax.swing.JTextField();
        tfStok = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        tfSubtotal = new javax.swing.JTextField();
        btnBatal = new javax.swing.JButton();
        btnTambah = new javax.swing.JButton();
        lblKategori = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Tambah Sparepart");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(new javax.swing.border.SoftBevelBorder(javax.swing.border.BevelBorder.RAISED));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel1.setText("Nama Sparepart");

        cbSparepart.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "- Pilih Sparepart -", "SSD NvMe 512GB", "RAM DDR4 16GB", "RAM DDR4 8GB", "HDD 1TB" }));
        cbSparepart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbSparepartActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel3.setText("Katergori");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel4.setText("Harga Satuan");

        tfHargaSatuan.setEditable(false);
        tfHargaSatuan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfHargaSatuanActionPerformed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel5.setText("Stok Tersedia");

        sJumlah.setModel(new javax.swing.SpinnerNumberModel());
        sJumlah.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                sJumlahStateChanged(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel6.setText("Satuan");

        tfSatuan.setEditable(false);

        tfStok.setEditable(false);

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel7.setText("Jumlah");

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        jLabel8.setText("Subtotal");

        tfSubtotal.setEditable(false);

        btnBatal.setForeground(new java.awt.Color(255, 0, 51));
        btnBatal.setText("Batal");
        btnBatal.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBatalActionPerformed(evt);
            }
        });

        btnTambah.setBackground(new java.awt.Color(21, 100, 230));
        btnTambah.setForeground(new java.awt.Color(255, 255, 255));
        btnTambah.setText("+ Tambah Ke Keranjang");
        btnTambah.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTambahActionPerformed(evt);
            }
        });

        lblKategori.setText("-");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1)
                            .addComponent(jLabel4)
                            .addComponent(cbSparepart, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(tfHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, 124, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(33, 33, 33)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel3)
                                    .addComponent(lblKategori))
                                .addGap(32, 32, 32))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel5)
                                    .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(43, 43, 43)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel6)
                                    .addComponent(tfSatuan)))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(sJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(127, 127, 127)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfSubtotal)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel8)
                                .addGap(0, 0, Short.MAX_VALUE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnBatal)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))))
                .addContainerGap(13, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cbSparepart, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblKategori))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfHargaSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSatuan, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfStok, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(jLabel8))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sJumlah, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(tfSubtotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTambah, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(btnBatal))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void cbSparepartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbSparepartActionPerformed
        // 1. PENGAMAN: Pastikan combobox sudah siap dan tidak kosong
        if (cbSparepart.getSelectedItem() == null) {
            return;
        }

        // Ambil urutan index yang dipilih
        int pilihan = cbSparepart.getSelectedIndex();
        double hargaSatuan = 0;
        String kategori = "-";
        String satuan = "-";
        int stokSisa = 0;

        // 2. KONDISI DEFAULT: Jika kasir memilih index 0 ("- Pilih Sparepart -")
        if (pilihan == 0) {
            tfHargaSatuan.setText("");
            tfStok.setText("");
            tfSatuan.setText("");
            lblKategori.setText("-"); // Kembalikan label kategori jadi strip
            return; // Hentikan eksekusi kode di bawahnya
        }

        // 3. LOGIKA HARGA & KATEGORI
        switch (pilihan) {
            case 1:
                hargaSatuan = 750000;
                kategori = "Penyimpanan / Storage";
                satuan = "pcs";
                break;
            case 2:
                hargaSatuan = 550000;
                kategori = "Memori / RAM";
                satuan = "pcs";
                break;
            case 3:
                hargaSatuan = 300000;
                kategori = "Memori / RAM";
                satuan = "pcs";
                break;
            case 4:
                hargaSatuan = 525000;
                kategori = "Penyimpanan / Storage";
                satuan = "pcs";
                break;
            // Tambahkan case selanjutnya di sini jika sparepart bertambah
            default:
                hargaSatuan = 0;
                kategori = "-";
                satuan = "-";
                break;
        }

        // 4. PENGAMAN ARRAY: Mengambil stok dari array global secara aman
        try {
            stokSisa = stokGlobal[pilihan];
        } catch (Exception e) {
            stokSisa = 0; // Mencegah error jika array stokGlobal belum diisi lengkap
        }

        // 5. TAMPILKAN KE UI
        // Update Label Kategori
        lblKategori.setText(kategori);

        // Buat desimal format lokal (Rupiah)
        java.text.DecimalFormat df = new java.text.DecimalFormat("#,###");
        java.text.DecimalFormatSymbols dfs = new java.text.DecimalFormatSymbols();
        dfs.setGroupingSeparator('.');
        df.setDecimalFormatSymbols(dfs);

        // Tampilkan harga ke tfHargaSatuan
        tfHargaSatuan.setText(df.format(hargaSatuan));

        // Tampilkan stok dan satuan ke text field
        tfStok.setText(String.valueOf(stokSisa));
        tfSatuan.setText(satuan);

        // 6. UPDATE PERHITUNGAN
        // Panggil fungsi hitung agar subtotal langsung update saat harga berubah
        hitungSubtotalSparepart();
    }//GEN-LAST:event_cbSparepartActionPerformed

    private void sJumlahStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_sJumlahStateChanged
        hitungSubtotalSparepart();
    }//GEN-LAST:event_sJumlahStateChanged

    private void btnTambahActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTambahActionPerformed
        try {
            // Ambil nilai dari komponen
            String nama = cbSparepart.getSelectedItem().toString();
            int qty = (Integer) sJumlah.getValue();
            
            int stokTersedia = Integer.parseInt(tfStok.getText());
            
            if (qty > stokTersedia) {
                javax.swing.JOptionPane.showMessageDialog(this,
                        "Gagal! Stok " + nama + " tidak mencukupi.\nSisa stok saat ini hanya: " + stokTersedia,
                        "Stok Kurang",
                        javax.swing.JOptionPane.WARNING_MESSAGE);
                return;
            }
            
            // Validasi: Cegah jika kasir belum milih barang atau jumlahnya 0
            if (nama.contains("Pilih") || qty == 0) {
                javax.swing.JOptionPane.showMessageDialog(this, "Pilih barang dan pastikan jumlah lebih dari 0!", "Peringatan", javax.swing.JOptionPane.WARNING_MESSAGE);
                return; // Hentikan proses
            }
            
            // Ambil teks angka bertitik, lalu bersihkan titiknya sebelum dikonversi
            double harga = Double.parseDouble(tfHargaSatuan.getText().replace(".", "")); // Kolom harga satuan
            double subtotal = Double.parseDouble(tfSubtotal.getText().replace(".", "")); // Kolom subtotal

            // Potong stok di database sementara
            int indeksPilihan = cbSparepart.getSelectedIndex();
            
            // Ambil kode dari array statis
            String kodeBarang = kodeGlobal[indeksPilihan];
            
            // Bungkus ke dalam Array Object
            dataBaru = new Object[]{"", kodeBarang, nama, qty, (int) harga, (int) subtotal};
            
            stokGlobal[indeksPilihan] = stokGlobal[indeksPilihan] - qty;
            
            // Tutup pop-up
            this.dispose();
        } catch (Exception e) {
            javax.swing.JOptionPane.showMessageDialog(this, "Terjadi kesalahan sistem", "Error", javax.swing.JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btnTambahActionPerformed

    private void tfHargaSatuanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfHargaSatuanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfHargaSatuanActionPerformed

    private void btnBatalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBatalActionPerformed
        this.dispose();
    }//GEN-LAST:event_btnBatalActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogTambahSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogTambahSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogTambahSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogTambahSparepart.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogTambahSparepart dialog = new DialogTambahSparepart(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBatal;
    private javax.swing.JButton btnTambah;
    private javax.swing.JComboBox<String> cbSparepart;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblKategori;
    private javax.swing.JSpinner sJumlah;
    private javax.swing.JTextField tfHargaSatuan;
    private javax.swing.JTextField tfSatuan;
    private javax.swing.JTextField tfStok;
    private javax.swing.JTextField tfSubtotal;
    // End of variables declaration//GEN-END:variables
}
